In [1]:
import torch
import torch.nn as nn
m = nn.Softmax(dim=1) #注意是沿着那个维度计算
input = torch.randn(2,2)
print("input:")
print(input)
output = m(input)
print(output)


input:
tensor([[-0.5847, -0.5550],
        [ 0.9827, -0.1196]])
tensor([[0.4926, 0.5074],
        [0.7507, 0.2493]])


In [2]:
input = torch.Tensor([-1,-2,-3,-4])
m = nn.Softmax(dim=0) 
output = m(input)
print(output)

tensor([0.6439, 0.2369, 0.0871, 0.0321])


In [54]:
proposal = torch.Tensor([[[172.9160,  53.1629,  46.7309,  65.8460,  44.6887,  45.3407],
         [162.0257,  60.7390,  44.0523,  64.7651,  42.2220,  44.7367],
         [179.0024,  53.7884,  42.4490,  67.1689,  45.3391,  48.8719],
         [181.8581,  55.6569,  43.7422,  69.6309,  37.5283,  38.7935],
         [173.8341,  53.7287,  45.9613,  64.6712,  44.2307,  45.5341],
         [173.2160,  53.9935,  90.3983,  66.1348,  42.9525,  44.2509],
         [178.6917,  55.0030,  87.7949,  68.3032,  42.4487,  46.0229],
         [178.7652,  55.9662,  86.9395,  68.0065,  42.5493,  46.0183],
         [179.1359,  55.0274,  87.1426,  68.3838,  42.3723,  45.8333],
         [179.2320,  55.2510,  87.0303,  68.6657,  42.1542,  45.9588],
         [103.9501,  55.6445,  35.6466, 148.5112,  27.0300,  35.2377],
         [ 93.6760,  60.9326,  36.1184, 147.6433,  28.1504,  39.1108],
         [103.6072,  55.2036,  35.6772, 149.2269,  27.2429,  35.1321],
         [ 96.6570,  54.3819,  40.8309, 149.0087,  26.8965,  38.2263],
         [103.1070,  55.1415,  35.9368, 149.4533,  27.1619,  35.1206],
         [ 98.4851,  54.2000,  94.3045, 145.8950,  25.1254,  38.6844],
         [ 99.0919,  53.7244,  99.6395, 142.1874,  24.5100,  37.1115],
         [ 99.1681,  53.7878, 102.1708, 148.0829,  26.0536,  35.0694],
         [ 96.6852,  56.3042,  93.9394, 150.6047,  23.3274,  36.0730],
         [ 95.7325,  52.6799, 102.3278, 143.4821,  27.6216,  33.8230]]])

In [55]:
proposal.shape

torch.Size([1, 20, 6])

In [56]:
 proposal_class = torch.Tensor([[1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4]])

In [57]:
 proposal_class.shape

torch.Size([1, 20])

In [58]:
proposal_class = proposal_class.clone().cpu().numpy().astype(int)

In [68]:
 import numpy as np
class_bbox = []
for idx in range(proposal_class.min(), proposal_class.max()+1):
    proposal_info = {}
    # Find Out class_idx info
    print(idx)
    single_cls_idx = np.where(proposal_class[0] == idx)[-1]
    single_proposal = proposal[:, single_cls_idx]
    single_proposal = single_proposal[:, :, [2, 1, 0, 5, 4, 3]]
    weighted_proposal = single_proposal.numpy()
    single_proposal =weighted_proposal.mean(axis=1)
    class_bbox.append(single_proposal.squeeze())
print(class_bbox)

1
2
3
4
[array([ 44.587143,  55.41518 , 173.92726 ,  44.65538 ,  42.80176 ,
        66.41642 ], dtype=float32), array([ 87.86112 ,  55.048225, 177.80817 ,  45.61684 ,  42.4954  ,
        67.8988  ], dtype=float32), array([ 36.84198 ,  56.260822, 100.19946 ,  36.565502,  27.29634 ,
       148.76868 ], dtype=float32), array([ 98.476395,  54.13926 ,  97.83256 ,  36.15226 ,  25.327599,
       146.05043 ], dtype=float32)]


In [69]:
len(class_bbox)

4

In [65]:
class_bbox[0].shape


(1, 6)

In [64]:
class_bbox[1]

array([[ 87.86112 ,  55.048225, 177.80817 ,  45.61684 ,  42.4954  ,
         67.8988  ]], dtype=float32)

In [32]:
single_proposal

tensor([[[ 94.3045,  54.2000,  98.4851,  38.6844,  25.1254, 145.8950],
         [ 99.6395,  53.7244,  99.0919,  37.1115,  24.5100, 142.1874],
         [102.1708,  53.7878,  99.1681,  35.0694,  26.0536, 148.0829],
         [ 93.9394,  56.3042,  96.6852,  36.0730,  23.3274, 150.6047],
         [102.3278,  52.6799,  95.7325,  33.8230,  27.6216, 143.4821]]])

In [33]:
weighted_proposal = single_proposal
single_proposal =weighted_proposal.mean(axis=1)

In [34]:
single_proposal

tensor([[ 98.4764,  54.1393,  97.8326,  36.1523,  25.3276, 146.0504]])

In [35]:
single_proposal.shape

torch.Size([1, 6])

In [36]:
a = weighted_proposal.sum(axis=1)

In [37]:
a

tensor([[492.3820, 270.6963, 489.1628, 180.7613, 126.6380, 730.2521]])

In [38]:
a/5

tensor([[ 98.4764,  54.1393,  97.8326,  36.1523,  25.3276, 146.0504]])